#!/usr/bin/env python3
from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path


PROJECT_ROOT = Path(__file__).resolve().parents[1]
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

from src.trading.polymarket_orderbook_archive import DEFAULT_ORDERBOOK_ARCHIVE_DIR  # noqa: E402
from src.trading.weather_closed_backfill import DEFAULT_BACKFILL_DIR  # noqa: E402
from src.trading.weather_historical_evidence import (  # noqa: E402
    historical_evidence_from_replay_report,
    write_historical_evidence_supplements,
)
from src.trading.weather_paper_journal import DEFAULT_PAPER_JOURNAL_DIR  # noqa: E402
from src.trading.weather_strict_gate_queue import default_strict_gate_queue_dir  # noqa: E402
from src.trading.weather_strict_gate_replay import build_strict_gate_replay_report_from_dirs  # noqa: E402


def parse_args(argv: list[str] | None = None) -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Replay strict-gate paper-only queue records against archived orderbooks.",
    )
    parser.add_argument("--paper-journal-dir", default=str(DEFAULT_PAPER_JOURNAL_DIR))
    parser.add_argument("--backfill-dir", default=str(DEFAULT_BACKFILL_DIR))
    parser.add_argument(
        "--official-value-supplements",
        help="JSON/JSONL official final value supplements generated by weather_official_value_backfill_report.py.",
    )
    parser.add_argument("--strict-gate-queue-dir", default=None)
    parser.add_argument("--orderbook-archive-dir", default=str(DEFAULT_ORDERBOOK_ARCHIVE_DIR))
    parser.add_argument("--replay-time", default=None)
    parser.add_argument("--size", type=float, default=1.0)
    parser.add_argument(
        "--queue-name",
        action="append",
        dest="queue_names",
        help="Restrict replay to one or more strict-gate queue names.",
    )
    parser.add_argument(
        "--historical-evidence-supplements-only",
        action="store_true",
        help="Print replay fills as calibration-ready historical evidence JSONL instead of the full replay report.",
    )
    parser.add_argument(
        "--historical-evidence-output",
        help="Append calibration-ready historical evidence supplements to this JSONL path.",
    )
    return parser.parse_args(argv)


def main(argv: list[str] | None = None) -> None:
    args = parse_args(argv)
    report = build_strict_gate_replay_report_from_dirs(
        queue_dir=args.strict_gate_queue_dir or default_strict_gate_queue_dir(args.paper_journal_dir),
        orderbook_archive_dir=args.orderbook_archive_dir,
        journal_dir=args.paper_journal_dir,
        backfill_dir=args.backfill_dir,
        official_value_supplements_path=args.official_value_supplements,
        replay_time=args.replay_time,
        size=float(args.size),
        queue_names=args.queue_names,
    )
    if args.historical_evidence_output:
        report["historical_evidence_write"] = write_historical_evidence_supplements(
            report,
            output_path=args.historical_evidence_output,
        )
    if args.historical_evidence_supplements_only:
        evidence = historical_evidence_from_replay_report(report)
        for row in evidence.get("supplements") or []:
            print(json.dumps(row, ensure_ascii=False, sort_keys=True))
        return
    print(json.dumps(report, ensure_ascii=False, indent=2, sort_keys=True))


if __name__ == "__main__":
    main()
