#!/usr/bin/env python3
from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path


PROJECT_ROOT = Path(__file__).resolve().parents[1]
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

from src.trading.weather_closed_backfill import DEFAULT_BACKFILL_DIR  # noqa: E402
from src.trading.weather_settlement_calibration import (  # noqa: E402
    build_settlement_calibration_report_from_dir,
)


def parse_args(argv: list[str] | None = None) -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Build paper-only settlement-truth calibration diagnostics for closed weather markets.",
    )
    parser.add_argument("--backfill-dir", default=str(DEFAULT_BACKFILL_DIR))
    parser.add_argument(
        "--official-value-supplements",
        help="JSON/JSONL official final value supplements generated by weather_official_value_backfill_report.py.",
    )
    parser.add_argument(
        "--historical-evidence-supplements",
        help="JSON/JSONL pre-resolution probability and executable-entry evidence keyed by market/token.",
    )
    parser.add_argument("--min-official-truth-samples", type=int, default=30)
    parser.add_argument("--min-probability-score-samples", type=int, default=30)
    parser.add_argument("--min-resolved-pnl-samples", type=int, default=10)
    parser.add_argument("--min-official-truth-coverage", type=float, default=0.80)
    parser.add_argument("--max-sample-rows", type=int, default=20)
    parser.add_argument(
        "--summary-only",
        action="store_true",
        help="Drop row-level calibration, mismatch, and gap samples from stdout.",
    )
    return parser.parse_args(argv)


def main(argv: list[str] | None = None) -> None:
    args = parse_args(argv)
    report = build_settlement_calibration_report_from_dir(
        args.backfill_dir,
        official_value_supplements_path=args.official_value_supplements,
        historical_evidence_supplements_path=args.historical_evidence_supplements,
        min_official_truth_samples=args.min_official_truth_samples,
        min_probability_score_samples=args.min_probability_score_samples,
        min_resolved_pnl_samples=args.min_resolved_pnl_samples,
        min_official_truth_coverage=args.min_official_truth_coverage,
        max_sample_rows=args.max_sample_rows,
    )
    if args.summary_only:
        report = dict(report)
        report.pop("calibration_rows", None)
        report.pop("mismatch_samples", None)
        report.pop("gap_samples", None)
    print(json.dumps(report, ensure_ascii=False, indent=2, sort_keys=True))


if __name__ == "__main__":
    main()
