#!/usr/bin/env python3
from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path


PROJECT_ROOT = Path(__file__).resolve().parents[1]
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

from src.trading.weather_closed_backfill import DEFAULT_BACKFILL_DIR  # noqa: E402
from src.trading.weather_closed_replay_seed import build_closed_replay_seed_report_from_dir  # noqa: E402


def parse_args(argv: list[str] | None = None) -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Build a paper-only closed weather market replay seed report.",
    )
    parser.add_argument("--backfill-dir", default=str(DEFAULT_BACKFILL_DIR))
    parser.add_argument("--max-gap-samples", type=int, default=10)
    parser.add_argument(
        "--use-observation-store",
        action="store_true",
        help="Supplement missing official_final_value from the local official intraday observation store.",
    )
    parser.add_argument(
        "--official-value-supplements",
        help="JSON/JSONL supplements generated by weather_official_value_backfill_report.py.",
    )
    parser.add_argument(
        "--summary-only",
        action="store_true",
        help="Drop token-level seed rows from stdout while keeping aggregate diagnostics.",
    )
    return parser.parse_args(argv)


def main(argv: list[str] | None = None) -> None:
    args = parse_args(argv)
    report = build_closed_replay_seed_report_from_dir(
        args.backfill_dir,
        max_gap_samples=args.max_gap_samples,
        supplement_official_observations=args.use_observation_store,
        official_value_supplements_path=args.official_value_supplements,
    )
    if args.summary_only:
        report = dict(report)
        report.pop("seeds", None)
    print(json.dumps(report, ensure_ascii=False, indent=2, sort_keys=True))


if __name__ == "__main__":
    main()
