#!/usr/bin/env python3
from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path


PROJECT_ROOT = Path(__file__).resolve().parents[1]
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

from src.trading.polymarket_orderbook_archive import DEFAULT_ORDERBOOK_ARCHIVE_DIR  # noqa: E402
from src.trading.weather_closed_backfill import DEFAULT_BACKFILL_DIR  # noqa: E402
from src.trading.weather_closed_historical_replay import (  # noqa: E402
    build_preresolution_orderbook_replay_report_from_dirs,
)


def parse_args(argv: list[str] | None = None) -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Promote pre-resolution active orderbook archives into closed-market replay evidence.",
    )
    parser.add_argument("--backfill-dir", default=str(DEFAULT_BACKFILL_DIR))
    parser.add_argument("--orderbook-archive-dir", default=str(DEFAULT_ORDERBOOK_ARCHIVE_DIR))
    parser.add_argument(
        "--official-value-supplements",
        help="JSON/JSONL official final value supplements generated by weather_official_value_backfill_report.py.",
    )
    parser.add_argument("--replay-time")
    parser.add_argument("--size", type=float, default=1.0)
    parser.add_argument("--summary-only", action="store_true")
    parser.add_argument("--candidates-only", action="store_true")
    parser.add_argument("--historical-evidence-supplements-only", action="store_true")
    return parser.parse_args(argv)


def _print_jsonl(rows: list[dict]) -> None:
    for row in rows:
        print(json.dumps(row, ensure_ascii=False, sort_keys=True))


def main(argv: list[str] | None = None) -> None:
    args = parse_args(argv)
    report = build_preresolution_orderbook_replay_report_from_dirs(
        backfill_dir=args.backfill_dir,
        orderbook_archive_dir=args.orderbook_archive_dir,
        official_value_supplements_path=args.official_value_supplements,
        replay_time=args.replay_time,
        size=float(args.size),
    )
    if args.candidates_only:
        _print_jsonl(report.get("candidates") or [])
        return
    if args.historical_evidence_supplements_only:
        _print_jsonl((report.get("historical_evidence") or {}).get("supplements") or [])
        return
    if args.summary_only:
        report = dict(report)
        report.pop("candidates", None)
        report.pop("orderbook_snapshots", None)
        replay = dict(report.get("replay") or {})
        replay.pop("fills", None)
        report["replay"] = replay
        evidence = dict(report.get("historical_evidence") or {})
        evidence.pop("supplements", None)
        evidence.pop("gap_samples", None)
        report["historical_evidence"] = evidence
    print(json.dumps(report, ensure_ascii=False, indent=2, sort_keys=True))


if __name__ == "__main__":
    main()
